package main

import (
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"
)

const tpl = `// Code generated by build process; DO NOT EDIT.

package main

const DeviceId = %d
var SecretUuid = []byte{%s}
`

func main() {
	if len(os.Args) != 3 {
		log.Fatal("Usage: go run generate.go <DEVID> <UUID>")
	}
	devIdStr := os.Args[1]
	devId, err := strconv.Atoi(devIdStr)
	if err != nil {
		log.Fatalf("Error parsing integer argument '%s': %v", devIdStr, err)
	}
	secretUuid := os.Args[2]
	os.Stdout.WriteString(fmt.Sprintf(tpl, devId, hexStringToByteLiteral(secretUuid)))
}

func hexStringToByteLiteral(hexStr string) string {
	hexStr = strings.ToLower(hexStr)
	var parts []string
	for i := 0; i < len(hexStr); i += 2 {
		parts = append(parts, "0x"+hexStr[i:i+2])
	}
	return strings.Join(parts, ", ")
}
